# Generated by Django 5.2.4 on 2025-08-03 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='myapp.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('product_owner', 'Product Owner'), ('project_manager', 'Project Manager'), ('scrum_master', 'Scrum Master'), ('developer', 'Developer'), ('designer', 'Designer'), ('tester', 'Tester')], default='developer', max_length=50),
        ),
    ]
