# Generated by Django 5.2.4 on 2025-08-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_project_organization_alter_user_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuetype',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='issuetype',
            name='project',
        ),
    ]
