# Generated by Django 5.2.4 on 2025-10-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repo_full_name',
            field=models.CharField(blank=True, help_text='e.g., username/repo', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo_url',
            field=models.URLField(blank=True, help_text='e.g., https://github.com/username/repo', null=True),
        ),
    ]
