# Generated by Django 5.2.4 on 2025-10-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_project_github_repo_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_wip_limits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='sprint_duration',
            field=models.IntegerField(blank=True, help_text='Sprint duration in weeks', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sprint_start_date',
            field=models.DateField(blank=True, help_text='First sprint start date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='wip_limits',
            field=models.JSONField(blank=True, help_text='WIP limits per column', null=True),
        ),
    ]
