# Generated by Django 5.2.4 on 2025-10-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_project_enable_wip_limits_project_sprint_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_repo_full_name',
            field=models.CharField(blank=True, help_text='e.g., username/repo', max_length=255, null=True),
        ),
    ]
